jupyter-widgets/ipydatagrid

- .github/workflows/check.yml
Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>
> Add Github Actions

- .github/workflows/check.yml
We need to update the README file urgently and GH Actions is blocking us from merging the PR.
> Temporarily disable GH Actions

- ipydatagrid/__init__.py
Fix missing imports in __init__.py.
Reported in #193
> Fix missing imports

- ipydatagrid/_version.py
- package.json
- setup.cfg
> Release 1.0.0

- ipydatagrid/_version.py
- package.json
> Release 1.0.1

- MANIFEST.in
- babel.config.js
> Fix for test failures

- .github/workflows/check.yml
- ipydatagrid/__init__.py
> Restore GH Actions

- README.md
- binder/environment.yml
- tox.ini
Add a Binder badge to the README to make it easier to try `ipydatagrid` in the browser.
To test this branch:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jtpio/ipydatagrid/binder?urlpath=lab%2Ftree%2Fexamples%2FDataGrid.ipynb)
> Add Binder files and badge

- ipydatagrid/datagrid.py
- tests/test_datagrid.py
**Issue number of the reported bug or feature request**: #208 
Fix the issue above
Tested in a Jupyter Notebook that the fix restores the expected behaviour.
No additional context.
> Fix synchronization for cell selections and change events

- ipydatagrid/_version.py
- package.json
> Release 0.1.2

- .github/workflows/check.yml
- .github/workflows/jest.yml
> GitHub Actions: add jest tests

- tests/test_datagrid.py
> Add more backend python tests

- ipydatagrid/_version.py
- package.json
> Release 1.0.3

- js/datagrid.ts
Making sure all front-end comm messages are piped through the widget view so we can take advantage of the various callback function wrappers the view provides. This allows python `print()` statements to correctly bubble up as `stdout` messages to the widget output area.
> Pipe comm messages through the widget view

- ipydatagrid/_version.py
- package.json
> Release 1.0.4

- .pre-commit-config.yaml
- ipydatagrid/_version.py
- package.json
- tests/test_datagrid.py
> Release 1.0.5

- RELEASE.md
- package-lock.json
> Add RELEASE.md and update package-lock.json

- js/core/datagrid.ts
- package-lock.json
- package.json
This PR bumps the lumino dependency to the latest version and introduces a fix for the auto-scroll issue when an a dialogue menu is opened on an unfocused element.
> Bump lumino dependency and fix auto scroll issue

- ipydatagrid/_version.py
- package.json
> Release 1.0.7

- ipydatagrid/_version.py
- package-lock.json
- package.json
> Release 1.1.0

- examples/Themes.ipynb
- ipydatagrid/_version.py
- package.json
> Release 1.1.1 🎉

- ipydatagrid/_version.py
- package-lock.json
- package.json
> Release 1.1.2

- ipydatagrid/_version.py
- package-lock.json
- package.json
> Release 1.1.3

- examples/Themes.ipynb
- ipydatagrid/datagrid.py
- js/feathergrid.ts
> Fix pandas-defined index name regression, FeatherGrid styling issue

- ipydatagrid/_version.py
- package-lock.json
- package.json
> Release 1.1.4

- ipydatagrid/_version.py
- package-lock.json
- package.json
> Release 1.1.7

- js/feathergrid.ts
Add event so that one can intercept the hyperlink click in the event that it doesn't open in a browser that support window.open
> Add event when hyperlinks are clicked

- ipydatagrid/_version.py
- package-lock.json
- package.json
> Release 1.1.8

- .github/workflows/check.yml
- .gitignore
- .pre-commit-config.yaml
- ipydatagrid/__init__.py
- setup.cfg
- tests/test_datagrid.py
- tox.ini
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
> Fix CI, bump linters and add 3.10 to the CI

- js/datagrid.ts
- package-lock.json
- setup.cfg
- tests/test_datagrid.py
This PR fixes an issue where scrollbars appear on small grids, rendered inside containers like ipywidgets containers such as HBox/VBox or Tasbs.
> Fix scrollbar issues when grid is rendered in a container

- ipydatagrid/_version.py
- package.json
> Release 1.1.9

- ipydatagrid/_version.py
- package.json
- setup.cfg
Also removing the hard pandas version pin here. Will figure out a different way of passing the tests for Python <= 3.6.
> Release 1.1.10

- ipydatagrid/_version.py
- package.json
> Release 1.1.11

- .github/workflows/update_galata_references.yml
> Update server port

- .pre-commit-config.yaml
- ipydatagrid/_version.py
- ipydatagrid/datagrid.py
- package-lock.json
- package.json
- pyproject.toml
> Update `black`, pin `jupyter_packaging`, fix serialization bug and release 1.1.12

- test-environment.yaml
Fixed an issue with the visual regression bot.
> Pin nodejs version

- .github/workflows/update_galata_references.yml
> Update bot to split testing envs for widgets7/8

- ipydatagrid/datagrid.py
- tests/test_datagrid.py
> Improve serialization to handle additional types

- js/feathergrid.ts
- js/mousehandler.ts
> Separate mouse handler from feathergrid

- README.md
*Issue number of the reported bug or feature request: No Issue
Updated commands in readme.md for development installation.
Ran the commands and tested running DataGrid.
No additional information.
> 📝 Updating development installation in readme

- package.json
> Remove unused file-loader

- ipydatagrid/_version.py
- package.json
> Release 1.1.13

- pyproject.toml
> Update version, add file exclusions for packaging

- js/core/filterMenu.ts
> Check event target element

- js/vegaexpr.ts
Fix https://github.com/bloomberg/ipydatagrid/issues/372
> Fix vega expressions

- .pre-commit-config.yaml
Fixes: https://github.com/bloomberg/ipydatagrid/issues/402
See: https://github.com/PyCQA/isort/pull/2078
> Increase the version of isort

- .github/workflows/check.yml
- .pre-commit-config.yaml
- ipydatagrid/_version.py
- ipydatagrid/datagrid.py
- package.json
- pyproject.toml
- tox.ini
Adds 3.11 to CI and bump tools while at it, and removed stale configurations.
> Release 1.2.0

- ipydatagrid/_version.py
- package.json
A clear and concise description of the changes you have made.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.
> Release 1.2.1

- ipydatagrid/_version.py
- package.json
- pyproject.toml
A clear and concise description of the changes you have made.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.
> Release 1.3.1

- ipydatagrid/_version.py
- package.json
- pyproject.toml
A clear and concise description of the changes you have made.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.
> Release 1.3.2
