js/feathergrid.ts
js/keyhandler.ts

*Issue number of the reported bug or feature request: #203*
Added an `ipydatagrid`-specific KeyHandler class to control the behaviour of `keydown` events. This allows us to address the issue where users cannot enter command mode on notebooks due to events being intercepted in the hierarchy above the `ipydatagrid` canvas. The new behaviour for an Escape key press event is as follows:
* If selections exist on the grid, clear those but stay focused on the grid so that the user can keep using keyboard shortcuts to control the grid, should they wish to do so.
* If no selections exist on the grid, yield focus to the `body` tag on the page. Command mode will then be available.
Tested working as expected on both JupyterLab3 and Jupyter Notebook …

Add ipydatagrid-specific KeyHandler class to control keydown events 

---

ipydatagrid/datagrid.py

This PR makes the index and column names of dataframes returned from the `grid.get_visible_data()` method to be consistent with the index and column names of the original DataFrame passed to the `grid` constructor.

Improve view of returned DataFrame from get_visible_data()

---

ipydatagrid/datagrid.py

This PR fixes the issue reported in #213 .
- Selections applied **before** sorting are cleared after sorting (no changes made here).
- Selections applied **after** sorting will refer to the correct data model.

Fix selections after sorting or filtering

---

ipydatagrid/datagrid.py
tests/test_datagrid.py

*Issue number of the reported bug or feature request: #213 *
This is an iteration on #219 . We now separate the data model from the grid, allowing `SelectionHelper` to return selections based on JSON table schema objects. Also updated tests and added new ones.

Decoupling data model from grid, and refactoring SelectionHelper

---

package-lock.json
package.json

This PR changes the build script in `package.json` so that the resulting `npm pack`  tarball includes an nbextension bundle in a `dist` folder. This is needed for our published NPM package, which is relied on by `nbconvert` and `voila`. I'm also uploading an updated `package-lock.json` file which references version 1.0.4.

Fix build script so we include a dist folder with nbextension in build tarballs

---

js/vegaexpr.ts

This PR fixes a regression we attempted fixing in #173, where the `format` function call from `vega-functions` results in an error due to an internal `dataflow` property missing.

Fix the `format` call in `vega-functions`

---

ipydatagrid/cellrenderer.py
ipydatagrid/datagrid.py
js/cellrenderer.ts
js/datagrid.ts
js/feathergrid.ts

This PR adds styling/theming support for `ipydatagrid` by exposing some styling properties `lumino/datagrid` has available. There is some overlap with properties such as `backgroundColor` which can also be set by `TextRenderer`, but overall it does allow for more customisation of the grid's style by enabling setting style properties such as grid lines, etc.
We will add the following styles:
```python
import pandas as pd
import numpy as np
import ipydatagrid as g
np.random.seed(104)
rang = 20
df = pd.DataFrame(
data=[np.random.randint(0, 11, rang) for i in range(rang)],
index=[f'Row {i}' for i in range(rang)],
columns=[f'Col {i}' for i in range(rang)]
)
style = {
'voidColor': '#111',
'backgroundColor': 'purple',
'gridLineColor': 'red', …
```

Add Styling/Themes

---

examples/Nested Hierarchies.ipynb
ipydatagrid/datagrid.py
js/datagrid.ts
js/feathergrid.ts
tests/js/datagrid.test.ts

This PR adds support for corner header renderers via a `corner_renderer` traitlet. The current API behaviour is not changed - users who do not pass to the constructor or set the `corner_renderer` property on the `DataGrid` object, but do pass `header_renderer` will see the header renderer applied to the corner header too. If they do set a `corner_renderer` property then it will will override the header renderer - only applies to the corner header!
```python
import ipydatagrid as grid
import numpy as np
import pandas as pd
np.random.seed(565)
columns = [f'Col {x}' for x in "A B C D E F".split()]
index = [f'Row {x}' for x in range(1, 11)]
data = np.round(np.random.random((10, 6)), 2)
df = pd.DataFrame(index=index, columns=columns, data=data) …
```

Add support for corner header renderer

---

README.md

*Issue number of the reported bug or feature request: None*
404 error when clicking on license web link from GitHub README
The link work on my fork 
Congrats for this widget

Invalid LICENSE link in README

---

ipydatagrid/datagrid.py

Pandas provides it's own 'NA' object for cases where numpy NaN is not appropriate (e.g. string columns). This is not currently handled in _data_to_json (only pandas NaT values are handled).
Addresses #257 
Testing still in progress - need to set up testing

handle pandas NA #257

---

ipydatagrid/datagrid.py
tests/test_datagrid.py

Addresses two issues: #250 and #118 
When dealing with dataframes with index objects which are not `pandas.MultiIndex`, we now rename the default index name from 'index' to 'id' before applying `dataframe.reset_index()`. This ensures that the reserved 'index' keyword does not cause issues with numpy, and also allows users to use 'index' as a column name if they wish to do so. It is likely that users will already have a column named 'id' in their dataframe, and when that's the case, we adjust our index name from 'id' to 'id_0' and if 'id_0' exists, then we use 'id_1' and so forth.
The single "breaking" change here is that DataGrids which did not have an index name set, were rendered with 'index' as the name for their index column, and now …

Add index_name parameter, use 'key' as default index name

---

ipydatagrid/_version.py
ipydatagrid/datagrid.py
package-lock.json
package.json
tests/test_datagrid.py

The logic for index_name in 1.1.4 didn't account for index names of newly passed DataFrames after the grid has been instantiated. This PR adds logic for that and releases 1.1.5 with this fix.

Fix an issue in 1.1.4 / Release 1.1.5

---

ipydatagrid/datagrid.py

Fixes the data serialization for jupyter_client >=7
This fixes invalid JSON serialization where dictionary keys are not strings

Fix for jupyter_client 7

---

js/core/viewbasedjsonmodel.ts
js/datagrid.ts
tests/js/datagrid.test.ts

This PR fixes an issue where updating a DataGrid object with a new data model which has a different schema, results in the DataGrid object rendering with the old, incorrect schema.

Fix rendering

---

ipydatagrid/datagrid.py
tests/test_datagrid.py

The following code triggers an exception when jupyter_client>=7 is used:
```python
import pandas as pd
from ipydatagrid import DataGrid
col_names = [('Parent Column', 'SubCol 1'), ('Parent Column', 'SubCol 2')]
df = pd.DataFrame(data={i: [1, 2, 3] for i in col_names},
columns=col_names)
grid = DataGrid(df, layout={'height': '200px'})
grid
col_widths = {
('Parent Column', 'SubCol 1'): 100
}
grid.column_widths = col_widths
```
This is due to the serialization logic change where tuples are no longer implicitly converted to strings. Similar issue shown in #274 
This PR adds a fix such that tuples passed as traitlet keys in dictionaries are explicitly converted to strings at source.

Serialization: convert tuples to strings

---

ipydatagrid/datagrid.py
tests/test_datagrid.py

The `renderers` serialization was not returning valid JSON, this PR fixes it

Fix serialization issue

---

js/vegaexpr.ts

New PR after I messed up my repo ;)
Describe your changes
Replaced the lookbehind regex in vegaexpr.ts with a normal regex group. Since the resulting matches are anyway re-processed with another regex, the extra capture group in the match shouldn't affect the final result.
Testing performed
Ran python and js tests, confirmed working in jupyter lab in firefox and safari.

 Fix for #284 not working in Safari (mac/ios)

---

package.json

(Probably?) since the hatch migration #362 map files are included into the distribution. This PR prevents generating map files in a production build.

Exclude map files in production

---

js/plugin.ts

In the `datagridPlugin` plugin, the `IThemeManager` token is optional but in the implementation of the activation function, this token is considered available. This PR handles the case of missing this token.
N/A
This PR will help `ipydatagrid` work with the future version of Voila.

Handle the missing `IThemeManager` case

---

ipydatagrid/datagrid.py

The change should be a no-op in terms of what the function that I changed returns. The obj argument of this recursive function is not actually used anywhere --it only appears in the recursive call and not at the base cases.
`str(obj)` is a very expensive operation that we end up needlessly going through for O(rows) operations while initialising a DataGrid.
This change significantly improves performance for me: Initialising a DataGrid for a DataFrame of 30k rows goes from 2.4s to 0.4s.
Signed-off-by: Vasilis Themelis <vdthemelis@gmail.com>

Major performance improvement

---

ipydatagrid/cellrenderer.py

Every TextRenderer shares the same `Expr` (by default). This means that if I create two text renderers, and change the expression on one, it also changes the expression in the other TextRenderer.e.g.
```python
tr1 = TextRenderer()
tr2 = TextRenderer()
tr1.text_color.value = "'red'"
```
I think this should behave analogous to say a `.layout` widget, where they are not shared.
To be honest, this is not the original reason to create this PR. In solara, we cannot have widgets created at import  time, since each user would share the same widget, which breaks ipydatagrid in solara.
I hope one of the two reasons is compelling enough :)

fix: do not share the Expr for text_color and background_color

---

ipydatagrid/datagrid.py
tests/test_datagrid.py

Signed-off-by: Vasilis Themelis <vdthemelis@gmail.com>
Fixes #393
Allow showing NumPy arrays as normal arrays in the grid. There is no distinction made between normal arrays and NumPy arrays once they are serialised but I assume that this is fine as there is not difference between normal floats and NumPy floats either (say).
Added a small unit test to assert that no exception is thrown when initialising a DataGrid object out of a DataFrame that includes np.array objects of various shapes.
Also:
* Simplify the _data_to_json function in terms of branching;
* Remove unneeded checks for int;
* Eliminate unused argument of _data_to_json;
I also noticed that ipydatagrid flattens arrays before showing them on the grid. I might change that on a separate PR.

Serialise NumPy arrays as any other array

---

js/mousehandler.ts

Fixes https://github.com/bloomberg/ipydatagrid/issues/415
Replaced a call to a private Lumino function that stoped being exported: https://github.com/jupyterlab/lumino/commit/f4feada592291af9e1e3e22313969cbcd724fffd / https://github.com/jupyterlab/lumino/pull/319
The call is replaced with a call to a new copy of the (small) function we were previously calling.
Just manual testing of the selection functionality.
This is the bare minimum required to fix the issue in the description.
There are other issues when switching to JupyterLab 4.0. Would it be worth upgrading the dependencies of this library to Lumino or do we want to keep compatibility with older versions of JupyterLab?
This requires https://github.com/bloomberg/ipydatagrid/pull/419

Fix cell selection in Jupyter 4.0

---

examples/CellEditing.ipynb
ipydatagrid/datagrid.py
js/core/viewbasedjsonmodel.ts
js/datagrid.ts
tests/js/datagrid.test.ts

Fix #352
An equivalent to the current `set_cell_value` method, but for setting entire rows.
Manual Notebook tests + adding a unit test in JS
For users, it's more convenient/performant to have this kind of APIs than having to call `set_cell_value` many times. We may want to implement the equivalent for columns at some point.

Implement set_row_value method

---

.github/workflows/update_galata_references.yml

Since the JupyterLab 4 update, the bot does not work anymore as galata test logic changed. This PR fixes it.

Fix bot for updating snapshots

---

js/core/gridContextMenu.ts

*Issue number of the reported bug or feature request: #422*
Added a section of code that repositions the FeatherGridContextMenu widget to the actual click location, using the geometry of the page and document body. This fixes the bug in [https://github.com/bloomberg/ipydatagrid/issues/422](https://github.com/bloomberg/ipydatagrid/issues/422) (and also the original bug, documented in [https://github.com/voila-dashboards/voila/issues/930](https://github.com/voila-dashboards/voila/issues/930)), which is caused by changes in Lumino originally proposed in [https://github.com/jupyterlab/lumino/issues/329#issuecomment-1266200387](https://github.com/jupyterlab/lumino/issues/329#issuecomment-1266200387), along with the retention of absolute positioning for this element in …

Fixed FeatherGridContextMenu placement in jupyter notebook and voila

---

ipydatagrid/datagrid.py

auto_fit_columns should default to False in docstring
*Issue number of the reported bug or feature request: #370
Change docstring default to False

auto_fit_columns default docstring

---

js/core/gridContextMenu.ts

Reverts bloomberg/ipydatagrid#441
Fix the regression in https://github.com/bloomberg/ipydatagrid/issues/446. This is somewhat critical.
We should come up with a better fix for the voila issue.

Revert "Fixed FeatherGridContextMenu placement in jupyter notebook and voila"

---

pyproject.toml

😓 the version is specified four times in the repo. That's great for making mistakes.

Fix pyproject version

---

.github/workflows/update_galata_references.yml

A clear and concise description of the changes you have made.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.

Fix galata bot, missing hub package

---

examples/CellEditing.ipynb
examples/DataGrid.ipynb
examples/cars.json
ipydatagrid/__init__.py
ipydatagrid/cellrenderer.py
js/cellrenderer.ts
js/core/filterMenu.ts
js/core/viewbasedjsonmodel.ts
js/datagrid.ts
js/mousehandler.ts

Fix https://github.com/bloomberg/ipydatagrid/issues/253
This only works with JupyterLab 4.1.0 which ships a recent enough version of Lumino.

Image renderer

---

js/core/view.ts

*Issue number of the reported bug or feature request: #392*
Added a default value of 1 to row count method for the header row
Ran the test suite and repeated steps in issue

Display columns with no data

---

js/core/gridContextMenu.ts
js/feathergrid.ts

Added several option to the column context menu
* Option to clear sort selection
* Option to copy selection to the clipboard
* Option to download selection as a CSV
* Option to download the entire table as a CSV
* Option to clear current selection
* Added separators between sections of the menu
Since this is mostly just adding UI elements for existing capabilities only manual testing was performed in addition to running to the current test suite
Selection based options are greyed out when there is no current selection

Add options to menu

---

.github/workflows/check.yml
pyproject.toml
tox.ini

This PR updates the Python versions used in CI. Summary of changes:
1. Updated latest CPython version from 3.11 to 3.12. The project builds and tests pass locally for me using Python 3.12 on Ubuntu.
2. Where only a single Python version is required for a CI job, increase it from 3.11 to 3.12.
3. Remove Python 3.7 so that the minimum version supported is 3.8. This follows https://devguide.python.org/versions/ which shows that we are now beyond the end of Python 3.7's supported life.
4. Update version of PyPy from 3.7 to 3.9. This is the version of PyPy supported by the current NumPy release (https://pypi.org/project/numpy/1.26.4/#files).

Update Python versions used in CI

---

examples/ConditionalFormatting.ipynb
examples/Pandas.ipynb
ipydatagrid/cellrenderer.py
ipydatagrid/datagrid.py
tests/test_datagrid.py
ui-tests-ipw7/tests/notebooks/conditional_formatting.ipynb
ui-tests-ipw7/tests/notebooks/datagrid.ipynb
ui-tests-ipw8/tests/notebooks/conditional_formatting.ipynb
ui-tests-ipw8/tests/notebooks/datagrid.ipynb

This PR adds some sensible defaults for scales used in `BarRenderer.bar_value` so that they can be omitted by the user. If `min` or `max` arguments of a `DateScale`, `LinearScale` or `LogScale` are omitted, they are determined from the data in the corresponding column. An example from some of the example notebooks is that the previous use of
```python
BarRenderer(bar_value=DateScale(min=df[\"Dates\"][0], max=df[\"Dates\"][n - 1]))
```
can be replaced by
```python
BarRenderer(bar_value=DateScale())
```
The calculations occur in the `DataGrid` constructor on the Python side.
Also, `bar_value` now accepts `None` and will create either a `DateScale` or `LinearScale` depending on the data type of the corresponding column. `bar_value` already has a default of `0.0` and …

Use sensible defaults for BarRenderer.bar_value

---

README.md
package.json

This corrects the `jlpm watch` command used by developers to watch for code changes and automatically rebuild, and adds some extra documentation in the README describing its use.
Thanks to @gjmooney for explaining this to me.

Correct jlpm watch command

---

ipydatagrid/datagrid.py
js/datagrid.ts

*Issue number of the reported bug or feature request: #379*
I've tried to tackle the issue by leveraging the DataGrid `rowBackgroundColor`/`columnBackgroundColor` functionality.
I've tested locally spinning up a Jupyter lab per the instructions in the README.
rows:
columns:
dark mode:
**Note:** The "zebra striping" terminology comes from the underlying DataGrid, I don't know if there is a better name for it, but I couldn't think of one :)

Support 'zebra stripes' for rows or columns

---

js/datagrid.ts

Fix backward compatibility with <=1.2.1 serialized models

---

js/core/gridContextMenu.ts

Fixes issue #422.
The positioning of context menus using Voila, NbClassic and Notebook<7 is incorrect as they are added to the DOM as the last child of the `body` and so the reference element that they are positioned with respect to is not necessarily correct, although it is fine for Jupyter Lab (the most tested option). The solution is make them the first child of the `body` instead.
Longer term there will be an addition to `lumino` so that menus can be attached to the correct node straight away rather than this approach of having to detach and reattach them. This code can remain then as the menu will already be the body's first child at the point of testing so the detach and reattach will be avoided.
Screenshots of this PR working in the presence of scrolling for lab, voila, notebook 6, …

Fix context menu position on Voila, NbClassic and Notebook<7

---

ipydatagrid/datagrid.py

this allows users to use the SelectionHelper on visible data only.
I require this functionality in `ipyautoui` and have previously monkey-patched `DataGrid` to add it - 
in the version bump to >1.3 there have been updates to the SelectionHelper thus breaking my patch - 
I think that the functionality could be useful to others so it would be great to get it supported by the lib.
the update is very simple (see diff) and doesn't represent an additional maintainence burden.
*Issue number of the reported bug or feature request: #340*
I monkey-patched DataGrid and added the new features and confirmed it is working. 
I was having trouble setting up the dev env in this repo https://github.com/bloomberg/ipydatagrid/issues/510 so haven't been able to …

🚀 create a `selected_visible_cell_iterator` property

---

ipydatagrid/datagrid.py
js/datagrid.ts

Fix https://github.com/bloomberg/ipydatagrid/issues/512

Fix for frontend turning column names as integers into strings

---

js/core/filterMenu.ts

Fixes #530.
Fixes the correct display of "filter by" conditions for date-based columns selected in the filter menu. The changes are trivial, it looks like it was originally a copy-and-paste error.
Screenshot of the problem is in the associated issue, and here is one after this fix:
[Screencast from 2024-08-02 14-38-08.webm](https://github.com/user-attachments/assets/e361fa14-69e9-48f8-ae87-05a1b61dcf6c)

Fix correct display of date-based filter conditions

---

.github/workflows/check.yml
pyproject.toml
tox.ini

Drop support for python 3.8 as it has reached end of life (https://devguide.python.org/versions/).

Drop support for python 3.8

---

examples/Streaming.ipynb
examples/Trees_paris.ipynb
ipydatagrid/__init__.py
ipydatagrid/datagrid.py
js/core/deserialize.ts
js/core/filterMenu.ts
js/core/streamingview.ts
js/core/streamingviewbasedjsonmodel.ts
js/core/view.ts
js/core/viewbasedjsonmodel.ts
js/datagrid.ts
js/datasource.ts
js/feathergrid.ts
js/streamingfeathergrid.ts
package.json
tests/js/arrayUtils.test.ts
tests/js/filterMenu.test.ts
tests/js/viewbasedjsonmodel.test.ts
tox.ini
yarn.lock

Provide a new widget `StreamingDatagrid` which lazily requests data to the back-end upon scrolling/resizing the grid. It only requests data needed to render the current viewport.
This is a very early draft for discussion, it requires more testing.
[Screencast from 2024-04-08 11-34-30.webm](https://github.com/bloomberg/ipydatagrid/assets/21197331/f547b405-26d5-42e5-8aed-51ceb697e8be)
Wish-list for this PR to be merge-able:

Streaming Datagrid
